### ISSUE TITLE
preprocessing 관련 코드 수집

### ISSUE THREAD

**Issue by ssunggun2** [Cheyenne-cloud/mulcam_army#33]
- remove emoji
- 언어 구분
- 특수 문자 제거

**Comment by saul-atomrigs** [comment]
- 언어구분: langdetect 라이브러리 이용 중 (가벼우면서 나름 성능 괜찮은 듯 합니다)..
- 특수문자 제거: regex 이용해서 코드 작성 중입니다
- remove emoji : regex 또는 유니코드 해봄직합니다

**Comment by ssunggun2** [comment]
@solleedata 
- remove emoji : 이거 관련해서 full request에 예시 코드 올려놨습니다.
- 특수 문자 제거: 이거 관련해서 full request에 예시 코드 올려놨습니다. #31 #33
